use std::collections::{HashMap, HashSet};

use chrono::{DateTime, Local, Utc};

use crate::models::{QuotaResult, SpeedTestResult};

/// Line metadata for email template
#[derive(Debug, Clone)]
pub struct LineInfo {
    pub name: String,
    pub number: String,
    pub isp: String,
    pub description: String,
}

/// Build HTML email body for task notification
///
/// Color thresholds for row highlighting:
/// - quota_percentage > 90%: Orange row (#FFB347)
/// - quota_percentage > 75%: Yellow row (#FFEB99)
/// - Default: White row
pub fn build_task_notification_email(
    _task_name: &str,
    _task_id: i64,
    execution_time: DateTime<Utc>,
    speed_tests: Option<&[(LineInfo, Option<&SpeedTestResult>)]>,
    quota_checks: Option<&[(LineInfo, Option<&QuotaResult>)]>,
) -> String {
    let mut html = String::new();
    let local_time = execution_time.with_timezone(&Local);

    html.push_str("<!DOCTYPE html>\n<html>\n<head><meta charset=\"UTF-8\"></head>\n");
    html.push_str("<body style=\"font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 20px;\">\n");

    html.push_str(&format!(
        "<p style=\"color: #555; font-size: 14px;\"><strong>Execution Time:</strong> {}</p>\n",
        local_time.format("%Y-%m-%d %H:%M:%S")
    ));
    html.push_str("<hr style=\"border: none; border-top: 2px solid #3498db; margin: 15px 0;\">\n");

    match (speed_tests, quota_checks) {
        (Some(sr), Some(qr)) => build_combined_table(&mut html, sr, qr),
        (Some(sr), None) => build_speed_test_table(&mut html, sr),
        (None, Some(qr)) => build_quota_check_table(&mut html, qr),
        (None, None) => {}
    }

    html.push_str("<div style=\"margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #777; font-size: 12px;\">\n");
    html.push_str("<p>This email was automatically generated by NetNinja network monitoring system.</p>\n");
    html.push_str("</div>\n</body>\n</html>");

    html
}

/// Build a combined table when both speed test and quota check results exist
///
/// Layout matches the legacy email format with grouped column headers:
/// | Line Information (4) | Speedtest (2) | Quota Results (4) |
fn build_combined_table(
    html: &mut String,
    speed_results: &[(LineInfo, Option<&SpeedTestResult>)],
    quota_results: &[(LineInfo, Option<&QuotaResult>)],
) {
    // Build lookups by line name
    let mut speed_map: HashMap<&str, Option<&SpeedTestResult>> = HashMap::new();
    let mut quota_map: HashMap<&str, Option<&QuotaResult>> = HashMap::new();
    let mut info_map: HashMap<&str, &LineInfo> = HashMap::new();
    let mut line_names: Vec<&str> = Vec::new();
    let mut seen: HashSet<&str> = HashSet::new();

    for (info, result) in speed_results {
        speed_map.insert(&info.name, *result);
        info_map.insert(&info.name, info);
        if seen.insert(&info.name) {
            line_names.push(&info.name);
        }
    }
    for (info, result) in quota_results {
        quota_map.insert(&info.name, *result);
        info_map.entry(&info.name).or_insert(info);
        if seen.insert(&info.name) {
            line_names.push(&info.name);
        }
    }

    let gh = "background-color: #7A3B00; color: #ffffff; padding: 10px; text-align: center; font-weight: bold; font-size: 14px; border: 1px solid #6A2F00;";
    let ch = "background-color: #D4A017; color: #4A2800; padding: 8px 6px; text-align: center; font-weight: bold; font-size: 12px; border: 1px solid #C09015;";

    // Table with grouped headers
    html.push_str("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 13px;\">\n");
    html.push_str("<thead>\n");

    // Group header row
    html.push_str("<tr>\n");
    html.push_str(&format!("<th colspan=\"4\" style=\"{}\">Line Information</th>\n", gh));
    html.push_str(&format!("<th colspan=\"2\" style=\"{}\">Speedtest</th>\n", gh));
    html.push_str(&format!("<th colspan=\"4\" style=\"{}\">Quota Results</th>\n", gh));
    html.push_str("</tr>\n");

    // Column header row
    html.push_str("<tr>\n");
    for col in &["Number", "Name", "ISP", "Description", "Download", "Upload", "Used", "Remaining", "Renewal Date", "Balance"] {
        html.push_str(&format!("<th style=\"{}\">{}</th>\n", ch, col));
    }
    html.push_str("</tr>\n");
    html.push_str("</thead>\n<tbody>\n");

    if line_names.is_empty() {
        html.push_str("<tr><td colspan=\"10\" style=\"padding: 10px; text-align: center; color: #999; font-style: italic; border: 1px solid #ddd;\">No results</td></tr>\n");
    } else {
        for line_name in &line_names {
            let info = info_map[line_name];
            let speed = speed_map.get(line_name).copied().flatten();
            let quota = quota_map.get(line_name).copied().flatten();

            let quota_pct = quota.and_then(|q| q.quota_percentage).unwrap_or(0.0);
            let row_bg = if quota_pct > 90.0 {
                "background-color: #FFB347;"
            } else if quota_pct > 75.0 {
                "background-color: #FFEB99;"
            } else {
                ""
            };

            let (download, upload) = if let Some(st) = speed {
                (
                    st.download_speed.map(|s| format!("{:.2} Mbps", s)).unwrap_or_else(|| "N/A".into()),
                    st.upload_speed.map(|s| format!("{:.2} Mbps", s)).unwrap_or_else(|| "N/A".into()),
                )
            } else {
                ("N/A".into(), "N/A".into())
            };

            let (used, remaining, renewal, balance) = if let Some(qr) = quota {
                let used_val = qr.used_quota.map(|u| format!("{:.2}", u)).unwrap_or_else(|| "N/A".into());
                let pct_str = qr.quota_percentage.map(|p| format!(" ({:.1}%)", p)).unwrap_or_default();
                (
                    format!("{}{}", used_val, pct_str),
                    qr.remaining_quota.map(|r| format!("{:.2} GB", r)).unwrap_or_else(|| "N/A".into()),
                    qr.renewal_date.map(|d| d.format("%d-%m-%Y").to_string()).unwrap_or_else(|| "N/A".into()),
                    qr.balance.map(|b| format!("{:.2}", b)).unwrap_or_else(|| "N/A".into()),
                )
            } else {
                ("N/A".into(), "N/A".into(), "N/A".into(), "N/A".into())
            };

            let td = format!("padding: 8px 6px; text-align: center; border: 1px solid #ddd; {}", row_bg);
            let td_green = format!("padding: 8px 6px; text-align: center; border: 1px solid #ddd; color: #27AE60; font-weight: bold; {}", row_bg);

            html.push_str(&format!("<tr style=\"{}\">\n", row_bg));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.number)));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.name)));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.isp)));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.description)));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, download));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, upload));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, used));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td_green, remaining));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, renewal));
            html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, balance));
            html.push_str("</tr>\n");
        }
    }

    html.push_str("</tbody>\n</table>\n");
}

/// Build standalone speed test results table
///
/// Layout: | Line Information (4) | Speed Test (2) |
fn build_speed_test_table(
    html: &mut String,
    speed_results: &[(LineInfo, Option<&SpeedTestResult>)],
) {
    let gh = "background-color: #7A3B00; color: #ffffff; padding: 10px; text-align: center; font-weight: bold; font-size: 14px; border: 1px solid #6A2F00;";
    let ch = "background-color: #D4A017; color: #4A2800; padding: 8px 6px; text-align: center; font-weight: bold; font-size: 12px; border: 1px solid #C09015;";

    html.push_str("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 13px;\">\n");
    html.push_str("<thead>\n");

    // Group header row
    html.push_str("<tr>\n");
    html.push_str(&format!("<th colspan=\"4\" style=\"{}\">Line Information</th>\n", gh));
    html.push_str(&format!("<th colspan=\"2\" style=\"{}\">Speedtest</th>\n", gh));
    html.push_str("</tr>\n");

    // Column header row
    html.push_str("<tr>\n");
    for col in &["Number", "Name", "ISP", "Description", "Download", "Upload"] {
        html.push_str(&format!("<th style=\"{}\">{}</th>\n", ch, col));
    }
    html.push_str("</tr>\n");
    html.push_str("</thead>\n<tbody>\n");

    if speed_results.is_empty() {
        html.push_str("<tr><td colspan=\"6\" style=\"padding: 10px; text-align: center; color: #999; font-style: italic; border: 1px solid #ddd;\">No speed test results</td></tr>\n");
    } else {
        let td = "padding: 8px 6px; text-align: center; border: 1px solid #ddd;";
        for (info, result) in speed_results {
            if let Some(st) = result {
                let download = st.download_speed.map(|s| format!("{:.2} Mbps", s)).unwrap_or_else(|| "N/A".into());
                let upload = st.upload_speed.map(|s| format!("{:.2} Mbps", s)).unwrap_or_else(|| "N/A".into());

                html.push_str("<tr>\n");
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.number)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.name)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.isp)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.description)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, download));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, upload));
                html.push_str("</tr>\n");
            } else {
                html.push_str("<tr>\n");
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.number)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.name)));
                html.push_str(&format!("<td colspan=\"4\" style=\"{}; color: #999; font-style: italic;\">No result</td>\n", td));
                html.push_str("</tr>\n");
            }
        }
    }

    html.push_str("</tbody>\n</table>\n");
}

/// Build standalone quota check results table
///
/// Layout: | Line Information (4) | Quota Results (4) |
fn build_quota_check_table(
    html: &mut String,
    quota_results: &[(LineInfo, Option<&QuotaResult>)],
) {
    let gh = "background-color: #7A3B00; color: #ffffff; padding: 10px; text-align: center; font-weight: bold; font-size: 14px; border: 1px solid #6A2F00;";
    let ch = "background-color: #D4A017; color: #4A2800; padding: 8px 6px; text-align: center; font-weight: bold; font-size: 12px; border: 1px solid #C09015;";

    html.push_str("<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 13px;\">\n");
    html.push_str("<thead>\n");

    // Group header row
    html.push_str("<tr>\n");
    html.push_str(&format!("<th colspan=\"4\" style=\"{}\">Line Information</th>\n", gh));
    html.push_str(&format!("<th colspan=\"4\" style=\"{}\">Quota Results</th>\n", gh));
    html.push_str("</tr>\n");

    // Column header row
    html.push_str("<tr>\n");
    for col in &["Number", "Name", "ISP", "Description", "Used", "Remaining", "Renewal Date", "Balance"] {
        html.push_str(&format!("<th style=\"{}\">{}</th>\n", ch, col));
    }
    html.push_str("</tr>\n");
    html.push_str("</thead>\n<tbody>\n");

    if quota_results.is_empty() {
        html.push_str("<tr><td colspan=\"8\" style=\"padding: 10px; text-align: center; color: #999; font-style: italic; border: 1px solid #ddd;\">No quota check results</td></tr>\n");
    } else {
        for (info, result) in quota_results {
            if let Some(qr) = result {
                let quota_pct = qr.quota_percentage.unwrap_or(0.0);
                let row_bg = if quota_pct > 90.0 {
                    "background-color: #FFB347;"
                } else if quota_pct > 75.0 {
                    "background-color: #FFEB99;"
                } else {
                    ""
                };

                let used_val = qr.used_quota.map(|u| format!("{:.2}", u)).unwrap_or_else(|| "N/A".into());
                let pct_str = qr.quota_percentage.map(|p| format!(" ({:.1}%)", p)).unwrap_or_default();
                let used = format!("{}{}", used_val, pct_str);
                let remaining = qr.remaining_quota.map(|r| format!("{:.2} GB", r)).unwrap_or_else(|| "N/A".into());
                let renewal = qr.renewal_date.map(|d| d.format("%d-%m-%Y").to_string()).unwrap_or_else(|| "N/A".into());
                let balance = qr.balance.map(|b| format!("{:.2}", b)).unwrap_or_else(|| "N/A".into());

                let td = format!("padding: 8px 6px; text-align: center; border: 1px solid #ddd; {}", row_bg);
                let td_green = format!("padding: 8px 6px; text-align: center; border: 1px solid #ddd; color: #27AE60; font-weight: bold; {}", row_bg);

                html.push_str(&format!("<tr style=\"{}\">\n", row_bg));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.number)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.name)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.isp)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.description)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, used));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td_green, remaining));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, renewal));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, balance));
                html.push_str("</tr>\n");
            } else {
                let td = "padding: 8px 6px; text-align: center; border: 1px solid #ddd;";
                html.push_str("<tr>\n");
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.number)));
                html.push_str(&format!("<td style=\"{}\">{}</td>\n", td, escape_html(&info.name)));
                html.push_str(&format!("<td colspan=\"6\" style=\"{}; color: #999; font-style: italic;\">No result</td>\n", td));
                html.push_str("</tr>\n");
            }
        }
    }

    html.push_str("</tbody>\n</table>\n");
}

/// Escape HTML special characters
fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_escape_html() {
        assert_eq!(escape_html("<script>alert('xss')</script>"),
                   "&lt;script&gt;alert(&#39;xss&#39;)&lt;/script&gt;");
    }

    #[test]
    fn test_build_email_no_results() {
        let html = build_task_notification_email(
            "Test Task",
            1,
            Utc::now(),
            None,
            None,
        );
        assert!(html.contains("Execution Time:"));
        assert!(!html.contains("Task ID:"));
        assert!(!html.contains("Combined Results"));
    }
}
